///////////////////////////////////////////////////////////
//  Interés.cs
//  Implementation of the Class Interés
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:33 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using InteresesBancarios;
namespace InteresesBancarios {
	public class Interés : Visitor {

		public Interés(){

		}

		public void visit(CuentaCorriente cc){

		}

		public void visit(CajaDeAhorro cda){

		}

		public void visit(TarjetaDeCrédito tdc){

		}

	}//end Interés

}//end namespace InteresesBancarios