///////////////////////////////////////////////////////////
//  Visitable.cs
//  Implementation of the Class Visitable
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:34 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace InteresesBancarios {
	public abstract class Visitable {

		public Visitable(){

		}

		public void accept(Visitor v){

		}

	}//end Visitable

}//end namespace InteresesBancarios