///////////////////////////////////////////////////////////
//  Visitor.cs
//  Implementation of the Class Visitor
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:34 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using InteresesBancarios;
namespace InteresesBancarios {
	public abstract class Visitor {

		public InteresesBancarios.Visitable m_Visitable;

		public Visitor(){

		}

		public void visit(CajaDeAhorro cda){

		}

		public void visit(CuentaCorriente cc){

		}

		public void visit(TarjetaDeCrédito tdc){

		}

	}//end Visitor

}//end namespace InteresesBancarios