///////////////////////////////////////////////////////////
//  CuentaCorriente.cs
//  Implementation of the Class CuentaCorriente
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:33 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class CuentaCorriente : Visitable {

		private float dinero;

		public CuentaCorriente(){

		}

		~CuentaCorriente(){

		}

		/// 
		/// <param name="Visitor"></param>
		public void accept(Visitor Visitor){

		}

	}//end CuentaCorriente

}//end namespace Package1