///////////////////////////////////////////////////////////
//  Interés.cs
//  Implementation of the Class Interés
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:33 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class Interés : Visitor {

		public Interés(){

		}

		~Interés(){

		}

		/// 
		/// <param name="cc"></param>
		public void visit(Cuenta Corriente cc){

		}

		/// 
		/// <param name="cda"></param>
		public void visit(Caja De Ahorro cda){

		}

		/// 
		/// <param name="tdc"></param>
		public void visit(Tarjeta De Crédito tdc){

		}

	}//end Interés

}//end namespace Package1