///////////////////////////////////////////////////////////
//  TarjetaDeCrédito.cs
//  Implementation of the Class TarjetaDeCrédito
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:33 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public class TarjetaDeCrédito : Visitable {

		private float dinero;

		public TarjetaDeCrédito(){

		}

		~TarjetaDeCrédito(){

		}

		/// 
		/// <param name="Visitor"></param>
		public void accept(Visitor Visitor){

		}

	}//end TarjetaDeCrédito

}//end namespace Package1