///////////////////////////////////////////////////////////
//  Visitor.cs
//  Implementation of the Class Visitor
//  Generated by Enterprise Architect
//  Created on:      11-Jul-2020 6:44:34 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Package1;
namespace Package1 {
	public abstract class Visitor {

		public Package1.Visitable m_Visitable;

		public Visitor(){

		}

		~Visitor(){

		}

		/// 
		/// <param name="cda"></param>
		public void visit(Caja De Ahorro cda){

		}

		/// 
		/// <param name="cc"></param>
		public void visit(Cuenta Corriente cc){

		}

		/// 
		/// <param name="tdc"></param>
		public void visit(Tarjeta De Crédito tdc){

		}

	}//end Visitor

}//end namespace Package1