///////////////////////////////////////////////////////////
//  Barrio.cs
//  Implementation of the Class Barrio
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:24 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Geografia {
	public class Barrio {

		private String codigoPostal;
		private String id;
		private String nombre;

		public Barrio(){

		}

		~Barrio(){

		}

		/// 
		/// <param name="_pais"></param>
		/// <param name="_provincia"></param>
		/// <param name="_ciudad"></param>
		public void llenar(País _pais, Provincia _provincia, Ciudad _ciudad){

		}

	}//end Barrio

}//end namespace Geografia