///////////////////////////////////////////////////////////
//  Ciudad.cs
//  Implementation of the Class Ciudad
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:28 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Geografia;
namespace Geografia {
	public class Ciudad {

		private Barrio barrios;
		private String id;
		private String nombre;
		public Geografia.Barrio m_Barrio;

		public Ciudad(){

		}

		~Ciudad(){

		}

		/// 
		/// <param name="_pais"></param>
		/// <param name="_provincia"></param>
		public void llenar(País _pais, Provincia _provincia){

		}

	}//end Ciudad

}//end namespace Geografia