///////////////////////////////////////////////////////////
//  Moneda.cs
//  Implementation of the Class Moneda
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:29 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Geografia {
	public class Moneda {

		private String id;
		private String simbolo;

		public Moneda(){

		}

		~Moneda(){

		}

		/// 
		/// <param name="_otroPais"></param>
		/// <param name="_cantidad"></param>
		public Double convertir(Pais _otroPais, Double _cantidad){

			return 0;
		}

	}//end Moneda

}//end namespace Geografia