///////////////////////////////////////////////////////////
//  Mundo.cs
//  Implementation of the Class Mundo
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:31 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Geografia;
namespace Geografia {
	public class Mundo {

		private País países;
		public Geografia.País m_País;

		public Mundo(){

		}

		~Mundo(){

		}

		public void llenar(){

		}

	}//end Mundo

}//end namespace Geografia