///////////////////////////////////////////////////////////
//  País.cs
//  Implementation of the Class País
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:33 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Geografia;
namespace Geografia {
	public class País {

		private String id;
		private Moneda moneda;
		private String nombre;
		private Provincia provincias;
		public Geografia.Provincia m_Provincia;
		public Geografia.Moneda m_Moneda;

		public País(){

		}

		~País(){

		}

		public void llenar(){

		}

	}//end País

}//end namespace Geografia