///////////////////////////////////////////////////////////
//  Provincia.cs
//  Implementation of the Class Provincia
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:34 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Geografia;
namespace Geografia {
	public class Provincia {

		private Ciudad ciudades;
		private String id;
		private String nombre;
		public Geografia.Ciudad m_Ciudad;

		public Provincia(){

		}

		~Provincia(){

		}

		/// 
		/// <param name="_pais"></param>
		public void llenar(Pais _pais){

		}

	}//end Provincia

}//end namespace Geografia