///////////////////////////////////////////////////////////
//  Pais.cs
//  Implementation of the Class Pais
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:29:33 PM
//  Original author: Ignacio Andre Keiniger
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using API_MercadoLibre;
using System.Net;
using System.Linq;

namespace API_MercadoLibre {
	public class Pais {

		public String id { get; set; }
		public String nombre { get; set; }
		public List<Provincia> provincias { get; set; }
		public Moneda moneda { get; set; }

		public Pais(String _id)
		{
			// Pido info del pais en la API
			WebRequest request_pais = HttpWebRequest.Create("https://api.mercadolibre.com/classified_locations/countries/" + _id);
			bool leidoCorrectamente = true;
			try
			{
				request_pais.GetResponse();
			}
			catch (System.Net.WebException e)
			{
				Console.WriteLine("{0} Exception caught.", e);
				leidoCorrectamente = false;
			}
			if (leidoCorrectamente)
			{
				WebResponse response_pais = request_pais.GetResponse();
				StreamReader reader_pais = new StreamReader(response_pais.GetResponseStream());

				// Guardo el JSON leido en un objeto
				string objetoJSON_pais = reader_pais.ReadToEnd();
				ML_Country ML_CountryObject = Newtonsoft.Json.JsonConvert.DeserializeObject<ML_Country>(objetoJSON_pais);

				id = ML_CountryObject.id;
				nombre = ML_CountryObject.name;
				moneda = new Moneda(ML_CountryObject.currency_id);

				llenarProvincias(ML_CountryObject.states);
			}
		}

		private void llenarProvincias(List<ML_PlaceSmall> _provincias)
		{
			provincias = new List<Provincia> { };
			// Checkeo que la lista no esté vacía
			if (_provincias?.Any() == true)
			{ 
				foreach (ML_PlaceSmall provincia in _provincias)
				{
					provincias.Add(new Provincia(id));
				}
			}
		}
	}
}