///////////////////////////////////////////////////////////
//  ML_Currency.cs
//  Implementation of the Class ML_Currency
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:32 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_Currency {

		private Int decimal_places;
		private String description;
		private String id;
		private String symbol;
		public ML_API.ML_Country m_ML_Country;

		public ML_Currency(){

		}

		~ML_Currency(){

		}

	}//end ML_Currency

}//end namespace ML_API