///////////////////////////////////////////////////////////
//  ML_City.cs
//  Implementation of the Class ML_City
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:29 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_City {

		private ML_PlaceSmall country;
		private ML_GeoInformation geo_information;
		private String id;
		private String name;
		private ML_PlaceSmall neighborhoods;
		private ML_PlaceSmall state;
		public ML_API.ML_PlaceSmall m_ML_PlaceSmall;
		public ML_API.ML_GeoInformation m_ML_GeoInformation;

		public ML_City(){

		}

		~ML_City(){

		}

	}//end ML_City

}//end namespace ML_API