///////////////////////////////////////////////////////////
//  ML_CurrencyConversion.cs
//  Implementation of the Class ML_CurrencyConversion
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:34 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_CurrencyConversion {

		private DateTime creation_date;
		private String currency_base;
		private String currency_quote;
		private Double inv_rate;
		private Double rate;
		private Double ratio;
		private DateTime valid_until;
		public ML_API.ML_Currency m_ML_Currency;

		public ML_CurrencyConversion(){

		}

		~ML_CurrencyConversion(){

		}

	}//end ML_CurrencyConversion

}//end namespace ML_API