///////////////////////////////////////////////////////////
//  ML_Country.cs
//  Implementation of the Class ML_Country
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:30 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_Country {

		private String currency_id;
		private String decimal_separator;
		private ML_GeoInformation geo_information;
		private String id;
		private String locale;
		private String name;
		private ML_PlaceSmall states;
		private String thousands_separator;
		public ML_API.ML_PlaceSmall m_ML_PlaceSmall;
		public ML_API.ML_GeoInformation m_ML_GeoInformation;

		public ML_Country(){

		}

		~ML_Country(){

		}

	}//end ML_Country

}//end namespace ML_API