///////////////////////////////////////////////////////////
//  ML_GeoInformation.cs
//  Implementation of the Class ML_GeoInformation
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:36 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_GeoInformation {

		private ML_Location location;
		public ML_API.ML_Location m_ML_Location;

		public ML_GeoInformation(){

		}

		~ML_GeoInformation(){

		}

	}//end ML_GeoInformation

}//end namespace ML_API