///////////////////////////////////////////////////////////
//  ML_Location.cs
//  Implementation of the Class ML_Location
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:38 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ML_API {
	public class ML_Location {

		private double latitude;
		private double longitude;

		public ML_Location(){

		}

		~ML_Location(){

		}

	}//end ML_Location

}//end namespace ML_API