///////////////////////////////////////////////////////////
//  ML_PlaceSmall.cs
//  Implementation of the Class ML_PlaceSmall
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:39 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_PlaceSmall {

		private String id;
		private String name;
		public ML_API.ML_ZipCode m_ML_ZipCode;

		public ML_PlaceSmall(){

		}

		~ML_PlaceSmall(){

		}

	}//end ML_PlaceSmall

}//end namespace ML_API