///////////////////////////////////////////////////////////
//  ML_State.cs
//  Implementation of the Class ML_State
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:41 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ML_API;
namespace ML_API {
	public class ML_State {

		private ML_PlaceSmall cities;
		private ML_PlaceSmall country;
		private ML_GeoInformation geo_information;
		private String id;
		private String name;
		public ML_API.ML_PlaceSmall m_ML_PlaceSmall;
		public ML_API.ML_GeoInformation m_ML_GeoInformation;

		public ML_State(){

		}

		~ML_State(){

		}

	}//end ML_State

}//end namespace ML_API