///////////////////////////////////////////////////////////
//  ML_ZipCode.cs
//  Implementation of the Class ML_ZipCode
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2020 11:30:43 PM
//  Original author: Fenjer
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace ML_API {
	public class ML_ZipCode {

		private ML_PlaceSmall city;
		private ML_PlaseSmall country;
		private ML_PlaseSmall state;
		private String zip_code;

		public ML_ZipCode(){

		}

		~ML_ZipCode(){

		}

	}//end ML_ZipCode

}//end namespace ML_API