///////////////////////////////////////////////////////////
//  Bobo.cs
//  Implementation of the Class Bobo
//  Generated by Enterprise Architect
//  Created on:      05-May-2020 4:12:57 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Bobo : Tipo {

	public Bobo(){

    }

}//end Bobo