///////////////////////////////////////////////////////////
//  Catalogo.cs
//  Implementation of the Class Catalogo
//  Generated by Enterprise Architect
//  Created on:      05-May-2020 4:12:57 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// This class (a) defines an Instance operation that lets clients access its
/// unique instance, and (b) may be responsible for creating its own unique
/// instance.
/// </summary>
public class Catalogo {

	private Catalogo catalogo;
	private Personaje personajesPredefinidos[100];
	public Personaje m_Personaje;

	protected Catalogo(){

	}

	public static Catalogo getInstance(){

		if (instance == null)
		{
			catalogo = new Catalogo();
		}
		else 
		{
			return catalogo;
		}
	}

	public Personaje getPersonajes()
	{
		return personajesPredefinidos;
	}

}//end Catalogo