///////////////////////////////////////////////////////////
//  Personaje.cs
//  Implementation of the Class Personaje
//  Generated by Enterprise Architect
//  Created on:      05-May-2020 4:12:57 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Personaje {

	private int altura;
	private string habilidades;
	private string imagen;
	private int inteligencia;
	private string nombre;
	private int peso;
	private Tipo tipo;
	public Tipo m_Tipo;

	public Personaje(){

	}

}//end Personaje