///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      05-May-2020 4:12:57 PM
//  Original author: Franco
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Usuario {

	private Personaje personajesCreados[100];
	private Personaje personajesSeleccionados[100];
	public Personaje m_Personaje;
	public Catalogo m_Catalogo;

	public Usuario(){

	}

	// Aca faltan los parametros para crear el personaje
	public void crearPersonaje(){
		Personaje nuevoPersonaje = new Personaje();
		personajesCreados.add(nuevoPersonaje);
	}

	/// 
	/// <param name="Personaje"></param>
	public void seleccionarPersonajePredefinido(Personaje _Personaje){
		foreach(Personaje personajeCreado in personajesCreados)
        {
			if(_Personaje == personajeCreado)
            {
				personajesSeleccionados.add(_Personaje);
				break;
            }
        }
		throw Exception;
	}

}//end Usuario